services:
  pardiff:
    build: ParDiff
    volumes:
      - ./output/pardiff:/output
      - ./tests:/tests
  popeye:
    build: netlifter
    volumes:
      - ./output/popeye:/output
      - ./tests:/tests
